### ISSUE TITLE
Try this one

### ISSUE THREAD

**Issue by ysmood** [doxout/promise-observer#1] opened 2015-10-12 13:40 UTC
https://jsfiddle.net/ysmood/musds0sv/

I never read your repo before, it's amazing to find something that is so similar with my implementation.

**Comment by spion** [comment] 2015-10-12 14:58
Haha yes, the API looks very similar.

I think there is one important difference though - promise-observer's `emit` returns a promise that is resolved when all the subscribers complete (so you can wait for them, then execute another action)

Another difference would be the intent - promise-observer wasn't really built to deal with UI events, but as a tool to decouple parts of node apps written with promises and expose events that would enable you to wire those parts up. The example given in the README is exactly the kind of thing its being used for in doxout

**Comment by ysmood** [comment] 2015-10-12 15:24
Read the examples of the API: https://github.com/ysmood/yaku#observableexecutor

`yaku/Observable` should also works well with backend node, it's a general purpose composable observable. Every `subscribe` will create a new observable, just like every `then` will create a new promise.

**Comment by spion** [comment] 2015-10-12 15:28
@ysmood you missed the part where `promise-observer`'s `emit` returns a promise. This is crucial for our use cases at doxbee. See the [example in the readme](https://github.com/doxout/promise-observer#example): the database transaction can only be closed after all observers complete their processing.

**Comment by ysmood** [comment] 2015-10-12 16:02
Your example is a little obscure for me to understand. Is there a full use case with all functions are defined?

**Comment by spion** [comment] 2015-10-12 16:28
Sorry, not at the moment.

The point is that this promise returned by `emit` in the second line in this code:

```
actuallyCreateBlogpost()
        .then(post => this.emit(post))
        // wait for all attached events to complete before commiting.
        .then(commitTransaction);
```

will actually wait for all of the below observers to process the post i.e. will wait for:

```
categorize(post).then(saveCategory).thenReturn(post)
```

```
index(post).then(saveIndex).thenReturn(post))
```

and

```
  var categorized = onPostCategorized.next(categorizedPost => categorizedPost.id == post.id);
  var indexed = onPostIndexed.next(indexedPost => indexedPost.id == post.id);
  return Promise.join(categorized, indexed, _ => sendEmailNotification(post))
```

Only after they're all complete, `commitTransaction` will run. The idea is that the categorization, the index and the job queuing (to send an email notification) will all have a chance to run in the same transaction and the calling code will know to wait for them before closing it. 

(Transactions are one particular use case where this is critical - we have other examples where we need to guarantee execution order e.g. every observer derived from pre-save observable hook must run before the actual save)

**Comment by ysmood** [comment] 2015-10-12 17:48
What will happen if `onPostCategorized` triggered twice but `onPostIndexed` only triggered once?

**Comment by spion** [comment] 2015-10-12 17:55
They're both triggered the exact same number of times because they're derived from `blogPostCreator. onCreated`. But if one of their promises returned a rejection, the promise returned by `emit(...)` will also get rejected.

Event sources can wait for event subscribers to "complete"; subscribers signal their completion by returning a promise. 

edit: I just remembered that I have working examples in the tests:

https://github.com/doxout/promise-observer/blob/master/test/index.js#L5-L20

**Comment by ysmood** [comment] 2015-10-12 20:45
Your implementation has some critical problems, run this code, you won't get any result:

``` js
var observer = require('promise-observer');
var Promise = require('bluebird');

var start, values = [];
var src = observer.create(function(emit) { start = emit; })

var a = src(function(val) { return Promise.delay(1).thenReturn(val + 1); })
var b = src(function(val) { return a.next().thenReturn(val + 2); });
var c = src(function(val) { return new Promise(function () {}); });

var push = values.push.bind(values);

a(push);
b(push);

setInterval(function () {
    return start(0).then(function() {
        console.log(values) // will never log
    });
}, 1000);
```

**Comment by ysmood** [comment] 2015-10-12 20:53
Yaku can achieve it easily and cleaner:

``` js
var Observable = require('yaku/lib/Observable');
function delay (t, v) { return new Promise(function (r) { setTimeout(r, t, v); }) }

var src = new Observable(function (emit) { setInterval(emit, 1000, 0); });

var a = src.subscribe(function (v) { return delay(20, v + 1); });
var b = src.subscribe(function (v) { return delay(10, v + 2); });
var c = src.subscribe(function (v) { return new Promise(function () {}); })

var out = Observable.all([a, b]);

out.subscribe(function (v) { console.log(v); }); // => log [1, 2] every 1 second
```

You can try it yourself: https://tonicdev.com/ysmood/yaku-lib-observable

**Comment by spion** [comment] 2015-10-12 22:24
Sorry, it seems like you didn't understand the use case of this library. Your example code doesn't allow for the _source observable_ to await for its observers to complete the processing _without knowing_ which those observers are, which is essential for separating parts of our system. Instead it requires the source observable to be aware of both `a` and `b`, which defeats the entire point (the module providing an extension point via an event, without being aware of that extension point's users)

To deal with potential issues with `next`, promise-observer includes a timeout functionality which can detect most deadlocks and generate an error containing one of the offending observers. But indeed, the `next` functionality is only used carefully and sparingly in our code, in cases where we don't have another choice.

**Comment by ysmood** [comment] 2015-10-12 22:38
No, it can.

``` js
var Observable = require('yaku/lib/Observable');
function delay (t, v) { return new Promise(function (r) { setTimeout(r, t, v); }) }

var src = new Observable(function (emit) { setInterval(emit, 1000, 0); });

src.subscribe(function (v) { return delay(20, v + 1); });
src.subscribe(function (v) { return delay(10, v + 2); });

// The src doesn't have know a or b now, we just await for all its subscribers.
var out = Observable.all(src.children); 

out.subscribe(function (v) { console.log(v); }); // => log [1, 2] every 1 second
```

**Comment by spion** [comment] 2015-10-12 23:19
Almost there, but not quite. You would also have to wait for those children's children, and those children's children's children and so on.

Additionally you would have to have the ability to deal with every single emit separately and see whether it has resulted with all observers being successful or not, as well as have the ability to return a promise that indicates that.

Basically you need emit to return a promise - there is no getting around it to get the same functionality:

``` js
var transaction = db.beginTransaction();
emit(transaction).then(_ => transaction.commit());

// ...

transactionObservable.subscribe(tx => tx.query('something'))
transactionObservable.subscribe(tx => tx.query('another-thing'))
```

Above we execute an action that ends the _particular_ transaction (and no other) only after all the queries resulting from that particular emit complete (for every generated transaction).

You could probably achieve it by adding a child that re-emits the transaction and recursively waiting for all children using Observe.all, but at that point I'd rather just use this library. Like I said in my first comment, it was designed to handle a different use case.

We do know that most use cases of `next()` would be better served by `Observe.all()` (much safer), and its our plan to do that as soon as we see an increased need to use `next()` in our code (so far it seems like its not necessary in most of our cases). What we'll probably end up implementing is something like [most's combine](https://github.com/cujojs/most/blob/master/docs/api.md#combine), but the issue here is that there needs to be a 1-to-1 correspondence for `emit()`'s waiting to make sense, so its tricky to pull it off correctly.

**Comment by ysmood** [comment] 2015-10-13 16:15
It's fairly easy for Yaku to do it, just lines of code:

``` js
var Observable = require('yaku/lib/Observable');
var delay = (t, v) => new Promise(r => setTimeout(r, t, v));

var src = new Observable(emit => setInterval(emit, 1000, 0));

src.subscribe(v => delay(20, v + 1));

// Here we could easily chain and pipe like promise.
src
    .subscribe(v => delay(10, v + 1))
    .subscribe(v => delay(10, v + 1));

// We just await for all the leaves of src.
var out = Observable.tree(src);

out.subscribe(v => console.log(v)); // => log [1, 2] every 1 second
```

With my implementation it's clearer to reason about what we are doing with the data structure.

**Comment by spion** [comment] 2015-10-13 16:56
Okay, let me try this way - here is a complete example runnable in node 

https://gist.github.com/spion/42528d641779983de252

Now can your observer do the same? Only allowed to change the `makeEnvironment` function.

**Comment by ysmood** [comment] 2015-10-14 04:01
I've solved your question. I also left you one.

**Comment by spion** [comment] 2015-10-14 10:23
I updated the example - it seems like your solution is sensitive to event timings

**Comment by ysmood** [comment] 2015-10-14 15:57
No, I test your code, no problem with Yaku. Are you using an old version of it?

**Comment by spion** [comment] 2015-10-14 18:01
@ysmood `npm ls` says

├── bluebird@2.10.2
├── promise-observer@1.0.12
└── yaku@0.10.0

`test-both.js` is: https://gist.github.com/spion/2ac942c47f86f5a8a687

```
17938 % node test-both.js
Yaku [ [ 1, 2, 3, 'close 1', 'close 1', 'close 1' ],
  [ 1, 2, 'close 2', 3, 'close 2' ],
  [ 1, 2, 3, 'close 3' ] ]
Unhandled rejection AssertionError: [ 1, 2, 3, 'close 1', 'close 1', 'close 1' ] deepEqual [ 1, 2, 3, 'close 1' ]
    at /Users/spion/Documents/yaku-obs/test-both.js:67:16
    at tryCatcher (/Users/spion/Documents/yaku-obs/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/spion/Documents/yaku-obs/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/spion/Documents/yaku-obs/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/spion/Documents/yaku-obs/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/spion/Documents/yaku-obs/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/spion/Documents/yaku-obs/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/spion/Documents/yaku-obs/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
PO [ [ 1, 2, 3, 'close 1' ],
  [ 1, 2, 3, 'close 2' ],
  [ 1, 2, 3, 'close 3' ] ]
```

I don't think its a bug in Yaku. Seems normal to me that the subscriptions to close the transactions are being triggered multiple times since they're all on the same observable. Thats why I keep saying that promise-observer is different. The promise returned by its `emit` only awaits for the subscriber promises generated by that particular event.

**Comment by ysmood** [comment] 2015-10-14 18:42
I don't want to waste time in your wrong direction anymore, we don't need observable at all to solve your question, observable shouldn't be used to do something like this, so I make this code for you:

``` js
var PObservable = require('promise-observer')
var Promise = require('bluebird');
var assert = require('assert');

function mkTransaction(tId) {
    var queries = []
    return {
        query: function query(q) { queries.push(q); return query },
        close: function() { queries.push('close ' + tId); return queries; }
    }
}

function mkRightTransaction() {
    var list = [];
    return {
        subscribe: function (fn) { list.push(fn); },
        start: function(id) {
            var tx = mkTransaction(id);
            return Promise.all(list.map(function (fn) {
                return fn(tx.query);
            })).then(tx.close);
        }
    }
}

function makePOEnvironment() {
    var emit;
    var onTransaction = PObservable.create(function(e) { emit = e; })
    return {
        subscribe: onTransaction,
        start: function(id) {
          var tx = mkTransaction(id);
          return emit(tx.query).then(tx.close)
        }
    }
}




function test(tag, makeEnvironment) {
    var env = makeEnvironment();

    var q1 = env.subscribe(function(q) {
        return Promise.resolve(1).delay(1).then(q)
    });
    var q2 = env.subscribe(function(q) {
        return Promise.resolve(2).delay(9).then(q)
    });
    var q3 = env.subscribe(function(q){
        return Promise.resolve(3).delay(20).then(q)
    });


    var p1 = env.start(1);
    var p2 = Promise.delay(25).then(function() {
        return env.start(2)
    });
    var p3 = Promise.delay(50).then(function() {
        return env.start(3);
    })
    var all = Promise.all([p1, p2, p3])
    all.then(function(items) {
        console.log(tag, items)
        assert.deepEqual(items[0], [1,2,3,'close 1']);
        assert.deepEqual(items[1], [1,2,3,'close 2']);
        assert.deepEqual(items[2], [1,2,3,'close 3']);
    })
}

test("Right", mkRightTransaction);
test("PO", makePOEnvironment);
```

**Comment by spion** [comment] 2015-10-14 19:24
That only works if there are no further "linked" (derived) observers (if its not a tree). You also need the remove and unlink methods, and yes, you pretty much get `promise-observer`

But yes, like I repeatedly said, the observable implementation of yaku should not be used to solve the problem I described above. To avoid misunderstandings like this for the future, I updated the readme to clarify the goals.

**Comment by spion** [comment] 2015-10-22 16:43
Idea: would the intent of the library be more clear if it was called `promise-emitter`? 

The description would be "Like a single-channel `EventEmitter`, with the ability to wait for the async subscribers when emitting"

edit: apparently promise-emitter is taken on npm :)

**Closed as completed** 2016-06-27 13:52 UTC
